import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { StateProvider } from "@/context/StateContext";
import QueryProvider from "@/components/queryProvider";
import Navbar from "@/components/Navbar";
import {Toaster} from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fiverr Clone",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <StateProvider>
            <div className=" relative flex flex-col h-screen justify-between">
              <Navbar />
              <div className={` mb-auto w-full mx-auto `}>
                {children}
              </div>
              <Footer />
            <Toaster/>
            </div>
          </StateProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
